CREATE DATABASE database_name;
USE database_name;

CREATE TABLE ORDERS(
    ID INT,
    CONSTRAINT ORDERS_ID PRIMARY KEY (ID),
    PRODUCT_NAME  VARCHAR(20),
    PRICE INT,
    DATE_ORDERED TIMESTAMP,
    DATE_CONFIRMED TIMESTAMP
);

